apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: rabbitexterno
      protocol: TCP
      port: 15672
      targetPort: 15672

    - name: rabbitinterno
      protocol: TCP
      port: 5672
      targetPort: 5672