apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - name: productexterno
      protocol: TCP
      port: 1111
      targetPort: 8080