apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - name: inventoryexterno
      protocol: TCP
      port: 8082
      targetPort: 8082