### Adiciona produto

POST http://localhost:8080/api/product
Content-Type: application/json

{
    "name": "Tênis",
    "description": "Tênis para correr e se exercitar",
    "brand": "adidas",
    "size": "50x30"
}
