apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: tre
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "123456"
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: tre
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "123456"
