apiVersion: v1
kind: Service
metadata:
  name: servico-compra-rabbit
spec:
  type: LoadBalancer
  selector:
    app: servico-compra-rabbit
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 8080
